### ISSUE TITLE
建议做成可扩展版，兼容批站、贴吧等一系列死🐎网站

### ISSUE THREAD

**Issue by yiruka114514** [Himself65/did-zhihu-close-down-today#5]

**Comment by Himself65** [comment]
It's a good idea, and easy to implement

**Comment by Himself65** [comment]
see: https://github.com/Himself65/website-failure-check-box

**Comment by yiruka114514** [comment]
It's really an amazing script. Thank you. XD

**Comment by seognil** [comment]
like that? -> https://steamstat.us/

**Comment by nicky258irl** [comment]
@seognil It's amazing. I wish the author could extend his script into sth like this some day.lol
